### ISSUE TITLE
Center items

### ISSUE THREAD

**Issue by rudnitskih** [anastasiia-emets/cryptokitties#5]
![image](https://user-images.githubusercontent.com/8848858/50758747-ba6cbd80-126b-11e9-996f-1323a06c24cd.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50789025-b4a2c680-12c3-11e9-8486-65c33688546e.png)

**Comment by anastasiia-emets** [comment]
![image](https://user-images.githubusercontent.com/40547968/50789101-f469ae00-12c3-11e9-81e3-9605978d4c76.png)
